### ISSUE TITLE
Error message when using control in EasyAdmin bundle

### ISSUE THREAD

**Issue by EddieK31** [zeliard91/FontAwesomePickerBundle#1]
When adding this control to an EasyAdmin form field I receive the following error:

> Undefined index: picker_options

This is the field configuration:

`- { property: icon, type: 'Redking\FontAwesomePickerBundle\Form\Type\FontAwesomeType' }`

Changing the field configuration to explictly include the picker_options value like below

` - { property: icon, type: 'Redking\FontAwesomePickerBundle\Form\Type\FontAwesomeType', type_options: { picker_options: { } } }`

results in the following error:

> The option "picker_options" does not exist. Defined options are: "action", "allow_extra_fields", "attr", "auto_initialize", "block_name", "by_reference", "compound", "constraints", "csrf_field_name", "csrf_message", "csrf_protection", "csrf_token_id", "csrf_token_manager", "data", "data_class", "disabled", "empty_data", "error_bubbling", "error_mapping", "extra_fields_message", "inherit_data", "invalid_message", "invalid_message_parameters", "label", "label_attr", "label_format", "mapped", "method", "post_max_size_message", "property_path", "required", "translation_domain", "trim", "upload_max_size_message", "validation_groups".

Using 
EasyAdmin: 1.17
Symfony 3.3.10
PHP 7.0.22

Issue resolved by adding the following code to the file: Redking\FontAwesomePickerBundle\Form\Type\FontAwesomeType

`    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'picker_options' => []
        ]);
    }
`

along with adding this use statement

`use Symfony\Component\OptionsResolver\OptionsResolver;
`

Once the above changes were made both ways of setting up the field worked properly.  Passing or not passing values and passed values worked as expected.

**Comment by zeliard91** [comment]
Thanks for bringing up this issue, I had not tested this bundle with Symfony 3.*.
It's now fixed in the latest version.
