### ISSUE TITLE
Error when form is loading

### ISSUE THREAD

**Issue by EddieK31** [zeliard91/FontAwesomePickerBundle#2]
Uncaught TypeError: $(...).iconpicker is not a function at <anonymous>:1:24
Using JQuery 3.2.1

iconpicker is loaded in jQuery.  Any suggestions?

**Comment by naumanafzal0313** [comment]
@EddieK31 have you found the solution?

**Comment by EddieK31** [comment]
Sorry, this was awhile ago and don't even remember what it was in reference to.  I looked over some code and didn't see anything to jog my memory.
